### ISSUE TITLE
The upload folder should be checked and created by os at start

### ISSUE THREAD

**Issue by DanBrown47** [arfazkhan/parser_proto#3]

**Comment by DanBrown47** [comment]
This is done to handle the error below

```
Traceback (most recent call last):
  File "/home/knight/tmpproj/parser_proto/venv/lib/python3.10/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/knight/tmpproj/parser_proto/venv/lib/python3.10/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/home/knight/tmpproj/parser_proto/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/knight/tmpproj/parser_proto/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/knight/tmpproj/parser_proto/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/knight/tmpproj/parser_proto/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/knight/tmpproj/parser_proto/main.py", line 16, in index
    uploaded_file.save(file_path)
  File "/home/knight/tmpproj/parser_proto/venv/lib/python3.10/site-packages/werkzeug/datastructures/file_storage.py", line 125, in save
    dst = open(dst, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'uploads/__Varsha_Mg_Resume.pdf
```
